### ISSUE TITLE
undefined reference to ...

### ISSUE THREAD

**Issue by su8** [Aversiste/substr#2]
Gentoo clang and gcc throws: 

![2018-01-03-135340_798x291_scrot](https://user-images.githubusercontent.com/29376083/34521480-3ee1e08c-f08e-11e7-8c88-9c9ad5147b67.png)

**Comment by tleguern** [comment]
This is “normal” as `getprogname` and `strtonum` are OpenBSD specific extensions to the libc. On Linux you can have them by installing libbsd and compile the project like this:

    LDADD=-lbsd CFLAGS="-D NEED_LIBBSD" make

I will update the documentation to reflect this.
